// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2019-05-29T20:59:15.858Z

const awsmobile = {
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
    aws_appsync_graphqlEndpoint: 'https://imrie3rq4fholpyttyfy2k4sv4.appsync-api.us-east-2.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-2',
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://tr8luwluia.execute-api.us-east-2.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'us-east-2'
        }
    ],
    aws_cognito_region: 'us-east-2',
    aws_project_region: 'us-east-2',
    aws_user_pools_id: 'us-east-2_0cZJf88IO',
    aws_user_pools_web_client_id: '605oc38n3d8uv1c5fvmn16dkt6'
};

export default awsmobile;
